### PR TITLE
(#7) - build step

### PR DESCRIPTION
**Pull request by calvinmetcalf**

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
@marfarma I'm still getting one error here.

**Comment by marfarma** [comment]
OK - I'm at a holding point until the group-by tests pass, both select & pivot -- unfortunately that grammar parsing stuff just is something I've never worked on before, and I'm not able to dig into the code.

Anything else you'd like me to do here?

**Comment by calvinmetcalf** [comment]
@marfarma I made a few more changes, do you want to look them over?
- the functions don't need to get redefined each and every time a new query is created, instead we can take them out of the closure
- the tests are making 2 length tests in different ways, switched them to do it the same way and to just use should (no need for expect)
- instead of commenting out the tests mocha has (I just learned about this 5 minutes ago) an `only` method that prevents them from running.
- favor functional declarations over functional expressions.

**Comment by marfarma** [comment]
It all makes sense.  Especially the functions not being re-defined for each query.

Re: "favor functional declarations over functional expressions" -- why?  Not arguing, just curious.

**Comment by calvinmetcalf** [comment]
considered the better way to do it in javascript, **all other things equal**, mainly because when you declare it the `function foo(){}` way the function is 'hoisted' so that you can call the function before it's declared (remarkably helpful and a thing I dislike about CoffeeScript) and you can call the function from inside itself (though try to avoid this).  

creating anonymous functions is something you should only need to do when making methods or when you are literally needing functions with no name (like when you are passing them to another function). 

that make sense?

**Comment by marfarma** [comment]
and the lightbulb above my head turns on.  Thanks.

I didn't know that about CoffeeScript.  I've been avoiding learning it - getting to know JavaScript well (it's only been the past six months that I've had a work related cause to do so) seems enough of a challenge without adding a layer of indirection.

**Comment by calvinmetcalf** [comment]
Good man,  all the good parts of CoffeeScript are becoming part of
JavaScript in ES6

**Comment by marfarma** [comment]
Good woman, you mean to say.  One of the two percent, at your service.

All the more reason to ignore CoffeeScript then. Are you using ES6 stuff (shim'd or compiled) yet?

**Comment by calvinmetcalf** [comment]
whoops my apologies, and firefox has some of the CoffeeScript inspired sugar, so I did a library to play around with that, but mainly the only ES6 stuff that I'd really use are the generator stuff that you can do in nodejs.

**Comment by calvinmetcalf** [comment]
merged them all in

**Pull request closed without merging**
