### PR TITLE
update to plugin v2

### PR DESCRIPTION
**Pull request by calvinmetcalf**
- we now just export a method with a name, executed in the context with this being the db
- due to it being on the prototype we only need to add it once

### CODE REVIEW

**Comment by nolanlawson** [comment]
:+1: except for the commit message.  Sorry for the delay, go ahead and push!

**Comment by dsharer** [comment]
I'll do better next time :)

**Comment by nolanlawson** [comment]
@dsharer Actually I meant Calvin's commit message.  We'll fix yours for ya; the first one's free.  :wink:

**Comment by calvinmetcalf** [comment]
fixed and merged

**Pull request closed without merging**
